### ISSUE TITLE
Modular suggestion

### ISSUE THREAD

**Issue by corroded** [vwall/compass-twitter-bootstrap#1]
Just a suggestion, shouldn't it be better if there's also an option to just include a module of the twitter bootstrap instead of the whole thing?

Like if I wanted to just include the fonts and forms, i can just do:

```
@import "compass_twitter_bootstrap/fonts"
@import "compass_twitter_bootstrap/forms"
```

**Comment by benschwarz** [comment]
The biggest issue with this suggestion is that the twitter bootstrap library uses classes rather than mixins. 
It really needs refactoring so that when you `require 'compass_twitter_bootstrap'` you only get generated CSS for features that you use (ah-la compass).

**Comment by corroded** [comment]
which needs refactoring? this gem or twitter's bootstrap itself? i can _try_ to help if i have some time this weekend if it is the fromer

**Comment by benschwarz** [comment]
I'd say that its not really "the compass way" to use loose classes the way that they have… so weather you want to include the buttons (for example) or not, they're there!  

A better approach would be to separate out the grids, buttons and all class powered items into mixins that can be dropped on elements with selectors. I might be so inclined to clean it up myself given the time and conviction. Of course, if you get there first it'd be awesome.

**Comment by corroded** [comment]
yeah i was thinking mixins like the "compass" way but yeah 'll just do a pull or something before i start to see if you've started it first when i get to have a chance to hack :)

**Comment by corroded** [comment]
We might need to discuss porting this more as some of the classes have "manual"(read: old-school) float clearing like the .clearfix class in the forms module. I've opened up an issue with bootstrap to try to help out with fixing this(https://github.com/twitter/bootstrap/issues/189) but we may have to decide on what to do next if they don't approve of the suggestion.

What do you think? I generally use a form > fieldset > ul > li structure, so refactoring forms.scss for _my_ needs may not necessarily be what you had in mind. I am planning to just go about this and use the compass clearfixes instead of their clearfix class for now since that way, the designer doesn't even need to add the clearfix class anywhere in his markup.

**Comment by benschwarz** [comment]
At a guess I'd think that you could use the compass-defined `clearfix` rather than the class definition.

**Comment by corroded** [comment]
hmmm yup that's what i was thinking, however, that means we have to assume what the parent container will be. We could do it by just assuming it would just be either be a div or li, right?

**Comment by benschwarz** [comment]
In my opinion `fieldset` is the tag to be used… Not sure how opinionated you want to be though :-)

**Comment by corroded** [comment]
i mean for the container for each input element :) we need to clear every time we float right? just using clearfix for fieldsets won't actually fix the floats for each `<li>` in it, right?(unless im mistaken with how the compass clearfix works)

**Comment by benschwarz** [comment]
Perhaps you should choose an element (please not an `<li>`—although I think there is a blog post in that topic) and write an example in comments where the `@mixin` lives… then if you decide to run some documentation software against it it'll be there for all to see. (or in the source).

**Comment by corroded** [comment]
Okay, will try to search for that blog post. I always thought it was the best thing to do(using lis for each form element), but I guess I was wrong :P How do you usually mark up your forms?

**Comment by benschwarz** [comment]
It totally works, but I think that lists should be used for what they're designed for. You could call any "collection" of things "a list" if you wanted to… it just doesn't mean its 'perfect'. But really, html semantics are meaningless.

**Comment by vwall** [comment]
The twitter bootstrap 1.3 and up is supposed to be more modular.  I've started porting this over, you can check it out in the develop branch if you want to use it.

**Comment by zacparker** [comment]
Curious what ever happened here, re: making bootstrap more modular.
