### ISSUE TITLE
replace_vars will break media-queries

### ISSUE THREAD

**Issue by tijsverkoyen** [vwall/compass-twitter-bootstrap#100]
In the convertscript there is a method [`replace_vars`](https://github.com/vwall/compass-twitter-bootstrap/blob/master/build/convert.rb#L99) which replaces @ with $, but this brakes media queries.

I think it should check if the string after the @ isn't `media` or `page`.

**Comment by tijsverkoyen** [comment]
Also not `-ms-keyframes` or `-o-keyframes`

**Comment by vwall** [comment]
Fixed in the 3.0 branch.  Will backport.
