### ISSUE TITLE
Font Awesome 3.0

### ISSUE THREAD

**Issue by lanterndev** [vwall/compass-twitter-bootstrap#103]
I'm using the latest release of compass_twitter_bootstrap (2.0.3) and wanted to be able to use Font Awesome 3.0 with it. Here is how to get them working together:
- Download Font Awesome 3.0 and add it to your app.
- Add a `<link rel="stylesheet"...>` for font-awesome.css _after_ the one for your compass-compiled css.
- Continue to `@import compass_twitter_bootstrap_awesome` from your sass stylesheet. If you switch to just `compass_twitter_bootstrap` the vertical alignment of icons inside buttons will be off.

Documenting this here in case it helps anyone else. Maybe it could go in the README? Seems worth it to mention you're not actually stuck with an old version of Font Awesome even if you're using the latest 2.0.3 ctb release.

**Comment by vwall** [comment]
This gem has been updated to 2.2.2. I'll look at adding Font Awesome 3.

**Comment by lanterndev** [comment]
> This gem has been updated to 2.2.2

Look at that! Just yesterday it seems. Impeccable timing!

> I'll look at adding Font Awesome 3.

Awesome, thanks! And thanks so much for the quick reply.

**Comment by vwall** [comment]
Updated FA to 3.0.1 in caf9db02c659fb8453e1d7d9272adee89e10af44
