### ISSUE TITLE
Modal background opacity is "80", not "0.80"

### ISSUE THREAD

**Issue by deanbrowne** [vwall/compass-twitter-bootstrap#108]
Very minor.

The modal's background is opaque instead of 80%.  On [line 20 of _modals.scss](https://github.com/vwall/compass-twitter-bootstrap/blob/master/stylesheets/compass_twitter_bootstrap/_modals.scss#L20) change:

``` scss
.modal-backdrop,
.modal-backdrop.fade.in {
  @include ctb-opacity(80);  // Should be 0.80
}
```

to:

``` scss
.modal-backdrop,
.modal-backdrop.fade.in {
  @include ctb-opacity(0.80);
}
```

**Comment by kelvinleehk** [comment]
+1. Is there any update on this issue?

**Comment by thetizzo** [comment]
This fix should be in the next release.  Thanks @deanbrowne
