### ISSUE TITLE
Installation Issues: ERROR:  While executing gem ... (RuntimeError)

### ISSUE THREAD

**Issue by wildscot** [vwall/compass-twitter-bootstrap#11]
$ gem 'compass_twitter_bootstrap'
ERROR:  While executing gem ... (RuntimeError)
    Unknown command compass_twitter_bootstrap

This is on an Ubuntu 10.04 server. Any help or alternative
installation ideas appreciated.

$ gem --version
1.8.10

$ gem list

**\* LOCAL GEMS ***

chunky_png (1.2.0)
compass (0.11.5)
compass-susy-plugin (0.9)
compass_twitter_bootstrap (0.1.7)
css_parser (1.1.9)
ffi (1.0.9)
fssm (0.2.7)
rake (0.9.2.2)
rb-inotify (0.8.8)
rubygems-update (1.8.10)
sass (3.1.5)

**Comment by vwall** [comment]
I think you mean

```
gem install compass_twitter_bootstrap
```

**Comment by firewalker06** [comment]
I'm having the same issue. compass_twitter_bootstrap gem is already installed but I can't run command.

I'm on 10.6 OS X.

$ gem --version
1.8.11

 gem list

**\* LOCAL GEMS ***

abstract (1.0.0)
actionmailer (3.0.7, 3.0.5, 2.3.5)
actionpack (3.0.7, 3.0.5, 2.3.5)
activemodel (3.0.7, 3.0.5)
activerecord (3.0.7, 3.0.5, 2.3.5)
activeresource (3.0.7, 3.0.5, 2.3.5)
activesupport (3.0.7, 3.0.5, 2.3.5)
arel (2.0.9)
builder (3.0.0, 2.1.2)
bundler (1.0.10)
chunky_png (1.2.0)
compass (0.11.5)
compass_twitter_bootstrap (0.1.8)

**Comment by vwall** [comment]
Are you still having this issue?

**Comment by spyworldxp** [comment]
I have this problem.

sudo gem install compass_twitter_bootstrap
Successfully installed compass_twitter_bootstrap-2.0.3
1 gem installed
Installing ri documentation for compass_twitter_bootstrap-2.0.3...
Installing RDoc documentation for compass_twitter_bootstrap-2.0.3...

gem 'compass_twitter_bootstrap'
ERROR:  While executing gem ... (RuntimeError)
    Unknown command compass_twitter_bootstrap

**Comment by xavisavvy** [comment]
I am having the same result.

**Comment by sukhjindersingh** [comment]
I am having the same issue getting following error 

ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command compass_twitter_bootstrap

$ gem list

**\* LOCAL GEMS ***

bigdecimal (1.1.0)
breakpoint (2.4.0)
bundler (1.5.0)
celluloid (0.15.2)
chunky_png (1.2.9)
coderay (1.1.0)
compass (1.0.0.alpha.17, 0.12.2)
compass-core (1.0.0.alpha.16)
compass-import-once (1.0.1)
compass_radix (0.0.25)
compass_twitter_bootstrap (2.3.1)
ffi (1.9.3)
formatador (0.2.4)
fssm (0.2.10)
guard (2.2.5)
io-console (0.3)
json (1.8.0)
listen (2.4.0, 1.1.6)
lumberjack (1.0.4)
method_source (0.8.2)
minitest (2.12.1, 2.5.1)
multi_json (1.8.2)
pry (0.9.12.4)
rake (10.0.4)
rb-fsevent (0.9.3)
rb-inotify (0.9.3)
rb-kqueue (0.2.0)
rdoc (3.12.2)
rubygems-update (2.1.11)
sass (3.3.0.rc.2, 3.2.13, 3.2.12)
sassy-maps (0.3.1)
slop (3.4.7)
thor (0.18.1)
timers (1.1.0)

It will great if you can provide solutions to this.
