### ISSUE TITLE
Bootstrap 2.3.0

### ISSUE THREAD

**Issue by jareware** [vwall/compass-twitter-bootstrap#110]
Hey,

Are there plans on reflecting the recent upstream release of 2.3.0 on this project, or are you concentrating efforts on 3.0-work?

**Comment by vwall** [comment]
I'll be doing a 2.3 version.

**Comment by nnarhinen** [comment]
:+1:

**Comment by cherifGsoul** [comment]
any news about this? thanks

**Comment by sethladd** [comment]
Looks done? Can you push to rubygems.org ?
