### ISSUE TITLE
Invalid semver

### ISSUE THREAD

**Issue by sindresorhus** [vwall/compass-twitter-bootstrap#112]
`v2.2.2.2` is not valid semver, use a build version instead, like `v2.2.2+2`

> A build version MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch version or pre-release version. Identifiers MUST be comprised of only ASCII alphanumerics and dash [0-9A-Za-z-]. Build versions satisfy and have a higher precedence than the associated normal version. Examples: 1.0.0+build.1, 1.3.7+build.11.e0f985a.

**Comment by thetizzo** [comment]
Closing since this isn't the current version number now.
