### ISSUE TITLE
Missing "unquote" in "ctb-transition" messes up transitions in webkit

### ISSUE THREAD

**Issue by ChristianHeckl** [vwall/compass-twitter-bootstrap#115]
https://makandracards.com/makandra/1058-remove-quotes-from-sass-mixin-arguments

**Comment by nishp1** [comment]
Just submitted a pull request that fixes this bug. https://github.com/vwall/compass-twitter-bootstrap/pull/116

**Comment by thetizzo** [comment]
Fixed this as part of a pull request in issue #116
