### ISSUE TITLE
Customzied bootstrap for compass?

### ISSUE THREAD

**Issue by ezmiller** [vwall/compass-twitter-bootstrap#134]
What if I do not need every part of twitter bootstrap for my project? Is there a way to choose which parts of bootstrap are imported?

**Comment by thetizzo** [comment]
For the bootstrap javascript you can require the individual files instead of requiring bootstrap-all. 

See here: https://github.com/vwall/compass-twitter-bootstrap/blob/master/vendor/assets/javascripts/bootstrap-all.js

**Comment by ezmiller** [comment]
Okay thank you for the speedy response!
