### ISSUE TITLE
Migrating to Bootstrap 2

### ISSUE THREAD

**Issue by olga-demchuk** [vwall/compass-twitter-bootstrap#18]
New Bootstrap released http://twitter.github.com/bootstrap/

**Comment by tmaier** [comment]
Just to give you an update.

I started off with [updating this gem](https://github.com/tmaier/compass-twitter-bootstrap) to Bootstrap 2.
_It's not done yet(!)_

The only issue I see at the moment is less code, like `#font > #family > .monospace` (see [original file](https://github.com/twitter/bootstrap/blob/master/less/code.less#L9))

Is there any reason why the converter does not use `sass-convert --from less --to scss`, as described [here](http://nex-3.com/posts/100-convert-less-to-scss)?

Will head on with my work tomorrow or later.
Feedback and ideas are always welcome.

**Comment by tmaier** [comment]
@vwall thank you for picking up this issue.
You did an awsome job!

the path to `@import` is not relative in [_compass_twitter_bootstrap_responsive.scss](https://github.com/vwall/compass-twitter-bootstrap/blob/master/stylesheets/_compass_twitter_bootstrap_responsive.scss).
This leads to the error message `File to import not found or unreadable: variables`.

**Comment by vwall** [comment]
I'll fix the import.  Last time I checked that sass-convert script didn't work with the current version of less.

**Comment by vwall** [comment]
Should be fixed with 3e2434603edcbb7559c92c83565bac6ca2500890
