### ISSUE TITLE
Jqeury method 'on' not found when loading bootstrap-alerts.js

### ISSUE THREAD

**Issue by chrisnicola** [vwall/compass-twitter-bootstrap#21]
This may just be some issue with bootstrap, but I have this in my application.js:

```
//= require jquery_ujs
//= require_tree .
//= require bootstrap-alert
//= require bootstrap-button
//= require bootstrap-tab
//= require bootstrap-tooltip
//= require bootstrap-transition
//= require bootstrap-dropdown
//= require bootstrap-modal
//= require bootstrap-popover
```

However on page load I get a method messing error from bootstrap-alert

TypeError: Object [object Object] has no method 'on'

which occurs at this line in bootstrap-alert.js

``` javascript
  $(function () {
    $('body').on('click.alert.data-api', dismiss, Alert.prototype.close)
  })
```

**Comment by chrisnicola** [comment]
AFAICT rails uses an old version of jquery, probably is missing this method. Just going to update it.

**Comment by uhbiv** [comment]
@lucisferre what was the resolution? I am trying this with Bootstrap v2.0.4 (jQuery 1.6.1) after including bootstrap-dropdown.js

`$('.dropdown-toggle').dropdown()`
TypeError: Object [object Object] has no method 'on'

Chrome error points to line 94 in bootstrap-dropdown.js
`$('html').on('click.dropdown.data-api', clearMenus)`

**Comment by uhbiv** [comment]
@lucisferre i just updated jquery version (from 1.6.1 to 1.8.2) and it worked. thanks for the inputs earlier which helped me solve it.
