### ISSUE TITLE
How can I customize bootstrap?

### ISSUE THREAD

**Issue by fancyoung** [vwall/compass-twitter-bootstrap#26]
I want config `$baseFontSize: 15px`.

It seemed that I need new a file and import all files which in https://github.com/vwall/compass-twitter-bootstrap/blob/master/stylesheets/_compass_twitter_bootstrap.scss

It's there better idea?

**Comment by vwall** [comment]
You'll have to switch the gem to this git branch and then just make sure $baseFontSize: 15px is before the compass_twitter_bootstrap import.

**Comment by fancyoung** [comment]
Thx. It works:)
