### ISSUE TITLE
Update to twitter bootstrap v2.0.2

### ISSUE THREAD

**Issue by brian-mann** [vwall/compass-twitter-bootstrap#50]
Twitter released v2.0.2 on March 12th -- and I don't believe this new version has been ported yet.

**Comment by toao** [comment]
+1

**Comment by dfross** [comment]
Bootstrap is now v2.0.3 - I think this project is dead.

**Comment by vwall** [comment]
Are people still using this?  I'll upgrade if so, just super busy.

**Comment by brian-mann** [comment]
Yes! It is a core part of our project.  v2.0.3 would be great!

**Comment by toao** [comment]
Same for us, an upgrade would be fabulous!

**Comment by marcusg** [comment]
+1

**Comment by wyuenho** [comment]
+1

**Comment by newlix** [comment]
+1
https://github.com/twitter/bootstrap/issues/2779
2.0.3 would be very nice!

**Comment by Kerrick** [comment]
:+1: I'll use the update!

**Comment by wyuenho** [comment]
Just commited changeset 883e2f4974732e356041de66a5681741329aff7e. This one should be a usable 2.0.3 update without compile time errors.

**Comment by rriemann** [comment]
So this issue can be closed?
