### ISSUE TITLE
Customize Grid

### ISSUE THREAD

**Issue by peschee** [vwall/compass-twitter-bootstrap#6]
Hi

Is there any way to customize the grid properties without having to replicate the entire package (with edited grid attributes in `_variables.scss`) and compile a customized gem?

Some of the values can be overriden even after an import of the package (e.g. color variables) by defining them, however, for example the number of columns in the grid has no effect when setting the `$gridColumns` variable after or before the `@import "compass_twitter_bootstrap";` import

**Comment by vwall** [comment]
You should be able to make your own variables.scss and import everything else on your own.

**Comment by peschee** [comment]
You mean without using the built gem but the source files directly? Should work, will try.

**Comment by vwall** [comment]
If you use @import "compass_twitter_bootstrap"; it will import everything for you. You can just create your own variables file then use

```
@import "compass_twitter_bootstrap/mixins";
@import "compass_twitter_bootstrap/scaffolding";
@import "compass_twitter_bootstrap/type";
@import "compass_twitter_bootstrap/forms";
@import "compass_twitter_bootstrap/tables";
@import "compass_twitter_bootstrap/patterns";
```

Just remember to also import compass before al of this.  I'll come up with something to make this process easier.

**Comment by peschee** [comment]
Awesome, thank you.

**Comment by johannesjo** [comment]
Hi! Any news on this one?
