### ISSUE TITLE
Let's agree to a prefix and always prefix mixins when converting

### ISSUE THREAD

**Issue by wyuenho** [vwall/compass-twitter-bootstrap#79]
As reported on issue #52, bootstrap mixins have names, parameters and behaviors that conflict with Compass'. However, since that ticket was closed and pull requests merged, maybe because I'm the only person unlucky enough to be affected by this issue, or that looking at the giant diff takes too much effort, I keep seeing newer pull requests coming in without the prefix or use a different one.

In my pull request #53, I opted to use "bootstrap-" as the prefix, but maybe that's not a good one. Can we agree on a prefixed please?

@vwall @tijsverkoyen @kristianmandrup?

**Comment by tijsverkoyen** [comment]
Personally I think `bootstrap-` is a fine proposal. It makes it very clear that the mixins are bootstrap related.

**Comment by tijsverkoyen** [comment]
@wyuenho You removed your comments on my pull-request. But is there a decent way to test the upgrade? Would be nice to see some docs about testing. I just downloaded the zip-file from bootstrap and replaced the generated CSS-file. I know this isn't the best way to test, but I couldn't think of a better way.

**Comment by wyuenho** [comment]
Depends on what you want to test, but if you just want to test for the signatures of the mixins, you can just get a list of them from Bootstrap and Compass' and compare them. If compass-twitter-bootstrap is included afterwards, the non-prefixed mixins will redefine Compass' mixins and trying to include them using Compass' signatures will result in either errors or incorrect output.

I'm aware of the difficulty in testing the conversion, so I spent a lot of time looking at the diff before committing, things like converting namespaces, loops and mixin references can be easily spotted this way, but other things are ore subtle. I spent a lot of time looking at the diff in my last pull request but I still managed to slip in a couple of bug, so...

**Comment by wyuenho** [comment]
I think `bootstrap-` is fine too, but it might conflict with other plugins that might also use the prefix `bootstrap-` to do something else. Maybe that's why @kristianmandrup chose `ctb-`?

**Comment by tijsverkoyen** [comment]
Hm, didn't thought about conflicts in other plugins. `ctb-` is more specific. So +1 for `ctb-`.

**Comment by wyuenho** [comment]
@kristianmandrup and @vwall what say you?

**Comment by kristianmandrup** [comment]
+1 for ctb- prefix of course. Needs to be concise but specific to this plugin in order to avoid conflicts.

**Comment by wyuenho** [comment]
@vwall can you put a note in the README to let people know to always use a prefix in the mixins and stick to _ctb-_?

**Comment by vwall** [comment]
+1 for ctb-

**Comment by tijsverkoyen** [comment]
ok. I included the prefix in my pull request: https://github.com/vwall/compass-twitter-bootstrap/pull/78

**Comment by tijsverkoyen** [comment]
I added a section in the README.md, see: https://github.com/vwall/compass-twitter-bootstrap/pull/82
